"""empty message
Revision ID: 12a1cb129d38
Revises: 455c2cde3f55
Create Date: 2023-01-25 13:47:49.702029
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a1cb129d38'
down_revision = '455c2cde3f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crearevento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreevento', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('integrantes', sa.String(length=120), nullable=False),
    sa.Column('publicooprivado', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombreevento'),
    sa.UniqueConstraint('publicooprivado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crearevento')
    # ### end Alembic commands ###