"""empty message

Revision ID: c3b9a4142e54
Revises: e23540f60e1c
Create Date: 2023-02-09 15:33:44.868669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b9a4142e54'
down_revision = 'e23540f60e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.String(length=300), nullable=False),
    sa.Column('lugar', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(length=120), nullable=True),
    sa.Column('asistentes', sa.String(), nullable=True),
    sa.Column('creador_evento', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['creador_evento'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_evento')
    )
    with op.batch_alter_table('crearevento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=256), nullable=True))
        batch_op.alter_column('ubicacion',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=600),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crearevento', schema=None) as batch_op:
        batch_op.alter_column('ubicacion',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('image_url')

    op.drop_table('events')
    # ### end Alembic commands ###