"""empty message

Revision ID: fa6f314c3864
Revises: e23540f60e1c
Create Date: 2023-02-02 15:23:11.467610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6f314c3864'
down_revision = 'e23540f60e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.String(length=300), nullable=False),
    sa.Column('lugar', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.String(length=120), nullable=False),
    sa.Column('hora', sa.String(length=120), nullable=False),
    sa.Column('asistentes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_evento')
    )
    with op.batch_alter_table('crearevento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizador_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['organizador_id'], ['id'])

    with op.batch_alter_table('unirseevento', schema=None) as batch_op:
        batch_op.drop_constraint('unirseevento_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unirseevento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('unirseevento_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('crearevento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organizador_id')

    op.drop_table('events')
    # ### end Alembic commands ###
